services:
  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./React/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key
    depends_on:
      - server

  db:
    image: mysql:oraclelinux9
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pasteleria
      TZ: "Europe/Madrid"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./BBDD/Pasteleria.sql:/docker-entrypoint-initdb.d/init.sql

  server:
      environment:
      - TZ=Europe/Madrid
      build: 
        context: ./Entidades/Pasteleria
        dockerfile: ./Dockerfile
      ports:
      - 9090:9090
      depends_on:
       db:
        condition: service_healthy
      

#  db:
#    image: mongo
#    ports:
#      - 27017:27017
#    env_file: ".env"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${USUARIO_MONGO}
#      MONGO_INITDB_ROOT_PASSWORD: ${CONTRASENA_MONGO}
#      MONGO_INITDB_DATABASE: mydatabase
#    volumes:
#      - ./db:/data/db