services:
  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./React/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key
    depends_on:
      - server

  db:
    image: mysql:oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  server:
      build: 
        context: ./Entidades/Pasteleria
        dockerfile: ./Dockerfile
      depends_on:
      - db


#  db:
#    image: mongo
#    ports:
#      - 27017:27017
#    env_file: ".env"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${USUARIO_MONGO}
#      MONGO_INITDB_ROOT_PASSWORD: ${CONTRASENA_MONGO}
#      MONGO_INITDB_DATABASE: mydatabase
#    volumes:
#      - ./db:/data/db