services:
  frontend:
    build:
      context: ./React
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./React:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key
    depends_on:
      - frontend

  db:
    image: mysql:oraclelinux9
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pasteleria
      TZ: "Europe/Madrid"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./BBDD/Pasteleria.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: 
      context: ./Entidades/Pasteleria
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - TZ=Europe/Madrid
    depends_on:
      db:
        condition: service_healthy